version: "3.3"
services:
  char_vs_rune:
    container_name: grpc-char_vs_rune
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - redis

  redis:
    container_name: redis
    image: "redis:5-alpine"
    ports:
      - 6379:6379

  influxdb:
    container_name: influxdb
    image: quay.io/influxdb/influxdb:v2.0.3
    ports:
      - 8086:8086
    volumes:
     # Mount for influxdb data directory and configuration.
      - ./sink/influxdbv2:/.influxdbv2:rw

  # Use the influx cli to set up an influxdb instance.
  influxdb_cli:
    container_name: influxdb-cli
    links:
      - influxdb
    image: quay.io/influxdb/influxdb:v2.0.3
    # Use the same configuration parameters in the telegraf configuration.
    entrypoint: influx setup --bucket char_vs_rune -t mytoken -o noprofit-org --username=myself --password=mypassword --host=http://influxdb:8086 -f
    # Wait until the influxd service in the influxdb container is bootstrapped before strting the setup of the influxdb instance . 
    restart: on-failure:20
    depends_on:
      - influxdb

  telegraf:
    container_name: telegraph
    image: docker.io/library/telegraf:latest
    ports:
      - 8125:8125
    links:
      - influxdb
    volumes:
      # Mount for custom telegraf configuration in par with the influxdb setup done through the influxdb CLI.
      - ./internal/configuration/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    restart: on-failure:10
    depends_on:
      - influxdb_cli
